### ISSUE TITLE
Support for XDG

### ISSUE THREAD

**Issue by dumblob** [NsCDE/NsCDE#1]
Any plans to support [XDG](https://specifications.freedesktop.org/basedir-spec/ )? At least the following `env` variables:

```
XDG_CONFIG_DIRS=/etc/xdg/
XDG_DATA_HOME=/home/myuser/.local/share/
XDG_CONFIG_HOME=/home/myuser/.config/
XDG_SEAT=seat0
XDG_VIDEOS_DIR=/home/myuser/video/
XDG_SESSION_TYPE=tty
XDG_PICTURES_DIR=/home/myuser/pics/
XDG_PUBLICSHARE_DIR=/home/myuser/
XDG_DOWNLOAD_DIR=/home/myuser/
XDG_MUSIC_DIR=/home/myuser/audio/
XDG_TEMPLATES_DIR=/home/myuser/
XDG_CACHE_HOME=/home/myuser/.cache/
XDG_SESSION_CLASS=user
XDG_DESKTOP_DIR=/home/myuser/
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
XDG_DOCUMENTS_DIR=/home/myuser/doc/
XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/home/myuser/.local/share/
```
E.g. currently `$FVWM_USERDIR` is used instead of telling the user to use `$XDG_CONFIG_HOME`. Also the default value `$HOME/.NsCDE` doesn't take XDG into account. I would say a more compatible option would be to set default to `$XDG_CONFIG_HOME/nscde/` and just ensure, that `$XDG_CONFIG_HOME` contained a sane widespread value - I'm myself using for my FVWM config `export XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/.config/}"` and so on for other XDG directories.

Btw. great work this whole NsCDE, thanks.

**Comment by NsCDE** [comment]
Hello,

Thanks for your comment.

I made it using $FVWM_USERDIR and set it to $[HOME]/.NsCDE just to separate NsCDE from potential other FVWM configuration which may be present already. Since FVWM is using $[HOME]/.fvwm I was not thinking a lot about other paths in user's HOME.
In my opinion, there is not much benefit of XDG_* variables apart from .config, and maybe cache directory. I don't see  how we can benefit here. I will change this if FVWM changes in the future.
But in the meantime, there should be no obstacles to redefine this in bin/nscde and config/NsCDE-Main.conf if wanted. Since I like flexibility, maybe I can make loading of initial variables from other file in the future, so it can be redefined in some file which is not part of the installation itself and overrun with new version.
All in all, I have already been thinking to "stadardize" this a bit and make it easy for packing into rpm, dep and such. In that case, data, libdir, bin, conf will be moved and /opt/NsCDE dissapear in the favor  of standard paths, but there is a lot of work there, specially in FvwmScripts which are using NSCDE_ROOT plus some other part of  the path. In that case, I will seriously consider XDG (in parts that are relevant to NsCDE that is). For now, since it is still beta, it behaves more like a custom "opt" instalation.

**Comment by dumblob** [comment]
>I will change this if FVWM changes in the future.

This will never happen IMHO (I'm using FVWM as my only environment on all computers for about 11 years and such proposals got immediately rejected with the excuse "it's for the future complete rewrite of FVWM" which doesn't exist at all - not even a single line of code IIRC).

>Since I like flexibility, maybe I can make loading of initial variables from other file in the future, so it can be redefined in some file which is not part of the installation itself and overrun with new version.

This sounds like the best compromise for the time being.

>For now, since it is still beta, it behaves more like a custom "opt" instalation.

Yep, that's why there is no hurry in this.
