### ISSUE TITLE
NsCDE freezes when deiconifying an icon on the desktop

### ISSUE THREAD

**Issue by simply1233** [NsCDE/NsCDE#113]
Whenever I deiconify an icon on the desktop, NsCDE completely locks up forcing me to reboot or kill Xorg.

**Comment by jhgalino** [comment]
I am experiencing the same issue.

**Comment by wallacewinfrey** [comment]
I am also experiencing this issue.

**Comment by simply1233** [comment]
I believe I found a way to fix it, instead of using the default fvwm, set it to fvwm3-git.

**Comment by marcdw1289** [comment]
Had this issue for some time on Garuda also.
I restarted fresh but don't remember if I used fvwm3 or the git version but the issue is still there.
If I'm working on anything important I have to remember not to iconify anything.
Noticed that any icons on the desktop will lose their image at time of lockup, producing gray-filled icons.

The keyboard still works so I can drop to a terminal and kill fvwm. That kills the whole desktop and returns me back to the display manager.

**Comment by b65sol** [comment]
@wallacewinfrey I'm actually able to reproduce this problem on arch all the way back to a1d503cc (I haven't checked further) which leads me to suspect its an arch-specific config responsible. Oddly, deiconifying with right-click works.

I don't know enough about FVWM (or arch repo management for that matter) to dig further. :(

I do have a ISO + qemu reproduction though.

**Comment by NsCDE** [comment]
Strange.

I will update my Arch VM and try this.

BTW, have you tried to type Ctrl+Alt+Escape (couple of times) maybe fvwm is stuck in some function.

I'm testing NsCDE on various popular distros and BSD's and never saw such freaky bug. As said, I will try this on Arch VM this days. Small change, but maybe fvwm is miscompiled or something like that, because Menu popup which appears on 1st mouse button click on the icon should is just a menu popup which are plenty of them in NsCDE, and shouldnt produce such dramatic results.

**Comment by b65sol** [comment]
ctrl-alt-escape does not do anything unfortunately. It is odd behavior. I was able to work around it by using fvwm3-git for my archiso environment.

Video (nscde-git, fvwm 2.6.8 from arch repository):

https://user-images.githubusercontent.com/25534016/188689868-77a4f46c-9b80-4116-9a14-22e1ad6364c7.mp4

If needed, I could upload the full archiso config + custom repo I use to reproduce this.

For the ISO used in the video all I have installed is this (plus their dependencies):

[packages.txt](https://github.com/NsCDE/NsCDE/files/9498971/packages.txt)

**Comment by NsCDE** [comment]
@b65sol 

Thanks for this very helpful video!

Amazing bug, probably something with default FVWM, maybe miscompiled. I will make tests this days and if it is FVWM bug forward to my "upstream".

**Comment by NsCDE** [comment]
Hi @b65sol @simply1233 @jhgalino @wallacewinfrey @marcdw1289 

I was not able to reproduce this with non-updated Arch with kernel 5.16.X, but after update to the latest 5.19.9 problem appears. I was able to reproduce this. Fvwm must be killed with "-9" to unlock, kill X and get login screen.

I see that Fvwm 2 package was NOT updated, and it is the same as before.

Problem is either with some X libraries, X server, or even with kernel in all this combinations. NsCDE is not for sure, fvwm too, but something from underlaying things mentioned above.

**Comment by NsCDE** [comment]
For all affected:

- Open /usr/share/NsCDE/fvwm/Functions.fvwmconf
- Near the line 1853 there is a function f_IconOpsBasicCtx
- At the end of second line of the function, you will find "Iconify Off"
- Prepend it with Schedule 250, like this:

`Schedule 250 Iconify Off`

- Open terminal.
- Execute `nscde_fvwmclnt f_ReadCfg Functions`

This temporary workaround works for me. This is not due to NsCDE nor fvwm, but some fix in X libraries which are breaking some window managers. Main author of fvwm3 is not sure why recent master branch of fvwm3 is immune to this, but we will find step by step where the code changed in a way to not hit this. Even then, if there are multiple icons, when deiconifying one icon, the other one may be left empty without drawing and label. Mouseover will refresh it, not a stopper, just a bit annying for now.

**Comment by ThomasAdam** [comment]
See:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016363

It's via X11's change here:  https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/157

Some work has already been done in FVWM to help with this (5c17c83df4605d2d97999740cf180af983298896) -- which is probably why some users are saying using `fvwm3-git` helps.

**Comment by b65sol** [comment]
@NsCDE Thanks much! That did correct it within my repro environment.

For others: If a double-click to deiconify also freezes FVWM, add the same schedule before `Iconify False` in `f_IconOps`

**Comment by cvjb** [comment]
@NsCDE @b65sol Thanks allot. Both schedule settings worked for me with NsCDE 2.2-1.2 and Opensuse Tumbleweed.

**Comment by NsCDE** [comment]
Remember guys, this is a temporary workaround. It will go off when either Xorg makes better patch, or fvwm adopts to this one. For now, I just want for things to work, so there are this silly timeouts. :-)

**Comment by tim78245** [comment]
this bug is present on fedora 37.

I'm using the package in fedora's repos, which is still on 2.1. I've also manually added the following:
https://github.com/NsCDE/NsCDE/commit/57803af0aa10e9702a54f2f0d5b941f98f05f167
https://github.com/NsCDE/NsCDE/commit/aeb43b9da0b161bb5a9ae69101397a081e845b77
https://github.com/NsCDE/NsCDE/commit/944f9070850c0f2d47c21d69ad5ec1e2245c56ac

There appears to be one issue still. When I have say my text editor iconified, and I open a text document in my file browser, it will then deiconify the text editor and open it in a new tab. This results in a crash.
