### ISSUE TITLE
Please feel free to make use of the fvwm forums

### ISSUE THREAD

**Issue by ThomasAdam** [NsCDE/NsCDE#12]
Hi @NsCDE,

Not sure if you're aware, but I've resurrected the [fvwmforums](https://fvwmforums.org).

Please do post anything you like there regarding `NsCDE`.  I've already extended this offer to `fvwm-crystal` and `fvwm-nightshade` who are making use of it.

If you're interested, I've created a category for `NsCDE` already (https://fvwmforums.org/c/fvwm-themes/nscde/).

Feel free to register an account.

If you've any questions, let me know.  Hope I'm not being too presumptuous.

Cheers,
Thomas

**Comment by NsCDE** [comment]
Hi @ThomasAdam 

Thank you very much for your personal invitation.

I saw the announcement on fvwm mailing list, but unfortunately I have so much work this days that I don't have much time for this (what I like). That's why you waited long for some traces and observation ...

I have now joined with my github account and will fill some info about NsCDE when I catch time.
