### ISSUE TITLE
Is there any way to change the FrontPanel Icon theme?

### ISSUE THREAD

**Issue by Lixkote** [NsCDE/NsCDE#122]
Is there any way to change the FrontPanel Icon theme to Papirus for example, by editing config files?

**Comment by NsCDE** [comment]
You can pick icons when clicking Front Panel launchers with 3rd mouse button and selecting "Change ths Button". By clicking in the default icon in Front Panel Icon Manager you can browse to alternative icon and pick it instead of default. Another option is to edit ~/.NsCDE/FrontPanel.actions. Pleas see the documentation for FrontPanel, subpanels and Front Panel Icon Manager.
