### ISSUE TITLE
Change One, Two.... button style/look

### ISSUE THREAD

**Issue by Lixkote** [NsCDE/NsCDE#124]
![image](https://user-images.githubusercontent.com/95425619/199039077-16c15a0d-50e4-41b2-b723-2e79b866ee10.png)

Where is located the pixmap/vector/svg etc for these buttons?
How can i restyle them?
 I want them to look like that
![image](https://user-images.githubusercontent.com/95425619/199042817-290647ae-571d-4205-b6f0-6493535095e5.png)

**Comment by NsCDE** [comment]
Hello @Lixkote

This is kind of central part of CDE look, so it is not really configurable in that way. Colors and names of the workspaces can be changed, as well as number of workspaces (1, 2, 4, 6 or 8).

You can make a local copy of /usr/share/NsCDE/fvwm/FrontPanel.fvwm2.fvwmconf (or FrontPanel.fvwm3.fvwmconf if using fvwm3 for NsCDE) as ~/.NsCDE/FrontPanel.fvwmconf and make changes for lock icon and Wsm* icons. You can find originals in the /usr/share/NsCDE/icons/NsCDE or /usr/local/share/NsCDE/icons/NsCDE look for Wsm* icons for page indicator, FpLock.xpm for lock, FpExit for Exit button. FpLite is a FvwmScript applet, you will have to use some gradient fvwm Colorset and rewrite FpLite complitely. For Workspace Manager (One, Two ...) you will have to redefine Colorsets 40-47 or at least 40-43 to have the same highlight and shadow color as background color. See autogenerated ~/.NsCDE/Colorset.fvwmgen.

All in all, probably couple of really busy days of work. I don't see what is the point of doing this, because NsCDE is all about 3D look and against so called "material" 3D look which is default if not only look of pretty much everything today, from android to Windows 10 and gnome.
