### ISSUE TITLE
Text out of dialog (font size problems)

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#14]
First of all thanks for creating NsCDE.

### Setup

- Resolution: `2560x1440`
- FVWM version: `2.6.9`
- NsCDE version: `fa987b4`
- Font: `Liberation Sans / Mono`

### Issue

I use NsCDE on the above setup and detected that some dialogs doesn't show the full text. Especially menu bars or parts in windows like the Style Manager. I've attached a screenshot which I hope could help to see the issue.

![2020-06-09-160418_1233x594_scrot](https://user-images.githubusercontent.com/315645/84157312-e3017400-aa6a-11ea-9413-392f2ce9c536.png)

If additional questions are needed feel free to ask.

### Idea

I expect it has something to do with the resolution, DPI and font size. But I'm not sure what would be the best way to debug it or set the correct values to make it look better.

```
$ env | grep DPI
NSCDE_FONT_DPI=144
DPI=96
NSCDE_DPI=96
```

```
$ xrdb -query -all | grep -i dpi
Xft.dpi:        144
```

**Comment by drscream** [comment]
Hello @NsCDE 

thanks a lot for your detailed feedback. Than I will try to modify the Font size based on my need. I need to admit that the default DPI of 96 with the currently used resolution provides a too small output for my daily work. That was the reason to switch to an higher value.

**Comment by NsCDE** [comment]
Hello @drscream 

I had impression that if bigger font is choosen, and this applies to GTK, Qt and X resources, default DPI should be ok, and "-Z" down-shape option from getfont script helper will downscale any excessive value for FvwmScript based apps. If NSCDE_FONT_DPI is higher than 96, this often does not help. It helps maybe for 120 DPI, but not for 144 DPI.

On the basis of this issue you opened, I'm thinking to extend "-Z" functionality of getfont, to be DPI aware and downscale fonts harder when DPI is higher.

This will allow to use Font Style Manager without post-editing NsCDE-Font-144dpi.conf or similar, and font sized in FvwmScript apps should be sane.

I will remain this issue opened. This has a base for improvement. Thanks!

**Comment by drscream** [comment]
Thanks again for your feedback. I would also like to provide some additional idea, which would help me a lot to not manually editing a lot of file:

Providing an option in the Style Manager to set / force the DPI value, which would result in the correct information in:

- Xdefaults.fontset
- Correct symlinked custom fontfile
- Setting in for xsettingsd
- maybe more which I've missed :-)

Also if I understand the DPI value correct, I used 144 because default is 96 so adding half of 96 would be a multiplier of this value. I use a different DPI setting also to have a bit more bigger icons (for example in firefox).

**Comment by NsCDE** [comment]
Hi @drscream 

I have tried and reporoduced this problems in virtual environment, so I belive I have mostly mitigated them in a way similar that you describe above: It handles Xft.dpi in $FVWM_USERDIR/Xdefaults.fontdefs, xsettingss, fontset symlink with a proper DPI in name ... you didn't missed anything I belive.
There were a lot of adjustments in FvwmScript applications to get as much as big font not to break widgets, widgets adjustment ... lot of calculations and some approximations and all that not to break prevailing 96 DPI default.

It is in pending_release branch. I must fix and tune some things still, and then I will release it.

Basically, you need to have XFT_USE_DPI in shell or X startup environment. This can be added in ~/.NsCDE/NsCDE.conf with SetEnv FVWM directive too. Re-login or use FvwmCommand to make this fvwm's environment, and launch Font Style Manager. Set some existing fontset with the same sizes as for 96 DPI and restart when asked on "OK".

The result will be bigger font in GTK and QT apps, and a bit smaller then on the rest of the system fonts in FvwmScript NsCDE apps, but they shouldn't break anymore.

Supported DPI are 96, 120, 144 and 192 (the last one is on the edge ...).

- 96 is 100%
- 120 is 125% (try it, maybe it suits you better)
- 144 is 150%
- 192 is 200%

After that, you can play with Font Style Manager to make fonts maybe 1 or 2 points smaller in some cases ... or not.

BTW, screen dpi (xrandr --dpi <value>) is one thing, and font DPI does not necessary correspondens to display DPI.

P. S.
Can you please tell me what screen are you using? What is diagonal size in inches and have you used some online calculator to calculate DPI? I think only devices with smaller size but bigger resolution will need DPI correction, otherwise plain font size increasing can be the solution.

**Comment by drscream** [comment]
Thanks a lot, I need to admit I didn't looked into all DPI features and how to handle them the best way for me.
I'm used an 14" notebook display with an 2560x1440 resolution. 

```
eDP1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
```

**Comment by NsCDE** [comment]
In case of 14" with this resolution, higher DPI for font is really justified. Try to play with bigger fonts mixed with lower (120) DPI to get some golden optimal. IF not, 144DPI should now work ok with pending_release. Freely try it, it will not clash with next release.

**Comment by drscream** [comment]
For me 144 DPI work well with the current `pending_release`. I will give it also a try with 120 DPI, but I assume the icons might be to small for me :-)

Thanks a lot for providing fixes :-)

**Comment by NsCDE** [comment]
Ok, this will be in 1.0 or next rc. Closing this.
