### ISSUE TITLE
Change FpLite to battery display for laptops?

### ISSUE THREAD

**Issue by u9000-Nine** [NsCDE/NsCDE#149]
I have looked all throughout the documentation and config files, but I have not been able to determine where the FpLite script is implemented, nor how to configure/reimplement it. Does anyone here know where that is? It would be very helpful to replace this with a battery display so that I know when my laptop’s about to die.

For now, I can check the battery in the terminal with the following alias. But since that requires I remember to check the battery before it runs out, it is not an ideal solution.
`alias bat='printf "%s%%, %s\\n" "$(cat /sys/class/power_supply/BAT0/capacity)" "$(cat /sys/class/power_supply/BAT0/status)"'`

**Comment by NsCDE** [comment]
It is /usr/lib/x86_64-linux-gnu/NsCDE/scripts/FpLite on Debian for example. On Fedora or Suse is probably /usr/lib/NsCDE/scripts/FpLite ... search "FpLite" fvwm script and "getla1" python helper.

You are welcome to modify this and deploy instead of default FpLite. May be in the future this can be made configurable (what FpLite will show), but not in the next release ... many fixes waiting, no time.

**Comment by u9000-Nine** [comment]
Thank you. I found `getla1` based on your advice, but I still have not been able to find `FpLite`. I will mess around with `getla1` and see if that’s enough to change it, and if not, I guess I’ll reach out to the Fedora maintainer.

<details><summary>Here’s the Fedora libexec tree if you’re interested:</summary>
<pre>/usr/libexec/NsCDE
├── acpimgr
├── appfinder
├── backdropmgr
├── bootstrap
├── colorconv
├── colormgr
├── colorpicker
├── confget
├── confset
├── fontmgr
├── fpclock
├── fpdoc
├── fpexec
├── fp_manage_subpanel
├── fpseticon
├── FvwmScripts
│   ├── GWM
│   ├── Notifier
│   └── Splash
├── generate_app_menus
├── generate_subpanels
├── getdpi
├── getfont
├── geticon
├── getla1
├── get_logical_screens
├── ised
├── keymenu
├── Linux_x86_64
│   ├── colorpicker
│   └── fpclock
├── migrate_nscde_1x_2x
├── mkpagemenu
├── palette_colorgen
├── strip_icon_path
├── style_managers.shlib
├── subpanel_menuitem_props
├── sysinfo
├── themegen
├── usleep
├── var_append
├── xdowrapper
└── xrandr_backer

3 directories, 41 files
</pre></details>

**Comment by tim78245** [comment]
Would this help?

`$ rpm -ql NsCDE | grep -i fplite
/usr/lib64/NsCDE/scripts/FpLite`

If you do manage to modify it to be a battery, remember to share it for others :)

What I do for getting more info in my panel is the following is swallowing an xterm window instead of one icon and KDE system's tray in another, which I detail here:
https://github.com/NsCDE/NsCDE/issues/42#issuecomment-1425087309

Both look surprisingly well integrated...

This gives me 3 lines of 6 characters for the terminal and 2 tray icons that on click gives me the rest of my tray icons.

Something else I have seen people do is swallow a dockapp:
https://www.dockapps.net/

**Comment by u9000-Nine** [comment]
> Would this help?
> 
> `$ rpm -ql NsCDE | grep -i fplite /usr/lib64/NsCDE/scripts/FpLite`

:facepalm: Thank you.

> If you do manage to modify it to be a battery, remember to share it for others :)

Yes, of course. I’ll comment it here and then resolve this issue when I do. Thanks everyone :-).
