### ISSUE TITLE
Provide easy support for different gtk-key-theme-name

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#16]
It would be nice if the install script would ask about the `gtk-key-theme-name` which the user like to use. I mostly stay with the default and not with `emacs` key theme for any application.

**Comment by NsCDE** [comment]
Note taken.

Since I didn't looked how to make custom gtk key bindings - for example to be in line with NsCDE, this was some old default.

Since Color Style Manager or any other tool will (except first run setup which is run once per new setup) not overwrite this in $FVWM_USERDIR/Xsettingsd.conf and in gtkrc-2.0 and 3.0, for now it is enough leave it as default. Whoever don't like it can edit this without fear that it will be silently overwritten.
I will leave this open and get back to this when I find out more, and maybe provide more general solution.

**Comment by NsCDE** [comment]
Solved in issue #40 closing this.
