### ISSUE TITLE
Workspace switcher not working on FreeBSD 12

### ISSUE THREAD

**Issue by BSDBro** [NsCDE/NsCDE#2]
Hi.
Thanks for this by the way, it is amazing.
After a few tweaks here and there I got this to work on FreeBSD 12 with Qt5. I am having an issue, however, with the workspace switcher not loading at all. I tried altering some settings under "manage workspaces" but those setting don't stick and upon reload the switcher still does not load. Any clues? I don't know what files to show here as I am very new to this desktop. Thanks

**Comment by NsCDE** [comment]
Hi

Strange.

Find fvwm output. Usually it is $HOME/.xsession-errors or something. See if NsCDE Log (xterm + tail -f that file) finds it for you - it is located on 7th subpanel.

Restart Workspace Manager (right click on root window -> "Restart Workspace Manager") and see for any errors in xsession errors.

But before all that, please checkout latest commit and try. It should be  pretty much stable now. Maybe you have cloned some bad intermediate commit, no matter that I test it before pushing to github.

**Comment by BSDBro** [comment]
Hi.
Thanks for the quick reply. I start NsCDE with .xinit and an custom .xinitrc file. Could that be the problem? There isn't any .xsession-errors file I can see. I also can't open the NsCDE log from the panel. I will try the latest commit and report back.

**Comment by BSDBro** [comment]
I just re-installed as per the official instructions. I think I found the error message which appears in console:

[code]
Aug 17 12:38:31 <hostname> FvwmScript[9839]: stack overflow detected: terminated
Aug 17 12:38:31 <hostname> FvwmScript[67647]: stack overflow detected: terminated
FrontPanel: Window 0x1600001 ("WSM") disappeared before swallow complete
[/code]

I will try adding the new commit and see if that helps.
Any clues from the error message above?
Thanks again.

**Comment by NsCDE** [comment]
Interesting. This is not error message from the NsCDE WSM.

Which version of fvwm you have installed? It should be 2.6.7 or 2.6.8.

Next, a quick grep in fvwm source, particulary FvwmScript source does not find this error message, which leads to the conslusion that this is some kind of system level hardening on FreeBSD which is in colission with FvwmScript or simply a sigsegv or similar.

Try to search the net for FreeBSD and "stack overflow detected" to see if you can workaround or override this. If not, please ask on fvwm developer list, since this may be a bug in fvwm's FvwmScript on FreeBSD. It is working on various Linux versions where I have tried it. Another possibility in the case of coredump is to try recompile fvwm with gcc or clang whatever is an alternative.

Also when this happens, see a recent /var/log/messages log lines and dmesg output.

**Comment by BSDBro** [comment]
Cool. Thanks for that. I have version 2.6.8. I did enabled a lot of system hardening options when I installed FreeBSD 12. I thought it was more of a Fvwm issue. I will try your suggestions, investigate and report back. Once again, thanks for this. It is even better than CDE itself and the workspace switcher isn't really that big a deal. :)

**Comment by NsCDE** [comment]
Please let me know if/when you get it working, so I can put warning for BSD stack protector in documentation, and eventually a workaround.

**Comment by BSDBro** [comment]
Thanks. I can't seem to get a .core file for the crash so I can't really investigate this further. Feel free to close this. Not sure how else to troubleshoot since this is really my first time using Fvwm.
