### ISSUE TITLE
1.0-rc24 doesn't start

### ISSUE THREAD

**Issue by pavroo** [NsCDE/NsCDE#31]
Hi
Just built rc24 on Debian stable and testing amd64, did no try on other arch yet, but... the builds went ok, but FVWM starts instead of NsCDE. Any clue, please?
regards
pavroo

**Comment by NsCDE** [comment]
Are you sure you have /opt/NsCDE or whenever you installed NsCDE?
Are you sure there is the a right nscde start wrapper path in /usr/share/xessions/nscde.desktop?
Are you sure you selected NsCDE in display manager, or have it in .xinitrc / .xsession
See ~/.xsession-errors ...
etc etc ...

Information provided here is not enough.

**Comment by pavroo** [comment]
Sure, all files installed ok, means there is /opt/NsCDE with all the files, /usr/share/xsession/nscde.desktop also exist, no .xinitrc no .xsession, the desktop starts via lightdm...
Enclosed xsession-errors.
[xsession-errors-20200903.txt](https://github.com/NsCDE/NsCDE/files/5169512/xsession-errors-20200903.txt)

**Comment by tux1c** [comment]
seconding @pavroo 
Gentoo Linux on amd64
running latest fvwm (2.6.9)
all dependencies are met
all system config files are in place as needed
also tried with a clean home directory with not prior user configuration

reverting to previous version of NsCDE runs flawlessly (also, I originally upgraded from the last version)

misc information:
running python3.7
.xsession-errors is empty

NsCDE simply falls back to vanilla fvwm configuration
restarting NsCDE from the context menu ("Restart NsCDE") after upgrading also messes up the desktop

**Comment by NsCDE** [comment]
Hi Guys,

I'm unable to reproduce this. I tested this on Debian and Fedora prior to release. I just booted Arch Linux VM now and tried there from targz package I put for download. It installs, everything works.

@pavroo 
xsession-errors does not contain ANY fvwm starting messages, just message that optional ~/.NsCDE/Xset.conf does not exist, then python trace of the fvwm-menu-desktop which indicates some inconsistency with your Python 3 installation, but this is not the reason why NsCDE should not start. Maybe Korn shell package is missing?

@tux1c if your .xsession-errors is empty, this can be due to lightdm impossibility to redirect stderr. Or some other display manager redirecting this to journalctl or other log file. That's why I prefer sddm.

Both: can you please put ">> /tmp/debugging_nscde.log 2>&1" on the line 126 of the /opt/NsCDE/bin/nscde logout and login? Here is the example:

Before:

exec $FVWM_BIN -f ${NSCDE_ROOT}/config/NsCDE-Main.conf $FVWM_OPTS

after:

exec $FVWM_BIN -f ${NSCDE_ROOT}/config/NsCDE-Main.conf $FVWM_OPTS >> /tmp/debugging_nscde.log 2>&1

Then attach me the contents of /tmp/debugging_nscde.log.

**Comment by pavroo** [comment]
Here you are.
[debugging_nscde.log](https://github.com/NsCDE/NsCDE/files/5174554/debugging_nscde.log)

**Comment by NsCDE** [comment]
Hi @pavroo 

Somehow it is hard to see anything there. There is no a SINGLE line of fvwm initialization there, and this should be stdout and stderr of fvwm -f /..../NsCDE-Main.conf. There should be at least some early echo. OTOH, python trace from fvwm-menu-desktop and vte terminal output are indicating that something else was executed but not FVWM with main NsCDE config.

From this information, I can only speculate that:

* there is no fvwm binary, or it is called "fvwm2" or "fvwm3" on your sistem. Please tell me FVWM version you are using with this setup
* something else, probably some wrapper is found as $FVWM_BIN, not fvwm binary directly.

You know, there is no a single line of fvwm binary or NsCDE processing something in debugging_nscde.log output. I don't have anything to start with, and in contrast to that, on my machine and in my virtual systems with various distros, all tests for release were passed. After this report, I repeated two of them. I never saw NsCDE "reverting to plain fvwm". This can only happen if $NSCDE_ROOT/config/NsCDE-Main.conf is missing, or it is unreadable, or display manager itself makes fallback to other desktop entry (fvwm) if starting NsCDE is not possible.

* fvwm -V
* ls -l /opt/NsCDE/config/NsCDE-Main.conf

**Comment by pavroo** [comment]
The 'fvwm' debian's package provides /usr/bin/fvwm2 binary, and installed alternatives:
`ls -l /usr/bin/fvwm
lrwxrwxrwx 1 root root 22 Jul  1 22:47 /usr/bin/fvwm -> /etc/alternatives/fvwm`
and:
`ls -l /etc/alternatives/fvwm
lrwxrwxrwx 1 root root 14 Jul  1 22:47 /etc/alternatives/fvwm -> /usr/bin/fvwm2`
So no real /usr/bin/fvwm binary.
The conf file exists:
`ls -l /opt/NsCDE/config/NsCDE-Main.conf
-rw-rw-r-- 1 pavroo pavroo 12490 Sep  2 21:34 /opt/NsCDE/config/NsCDE-Main.conf`
and fvwm version:
`fvwm -V
fvwm 2.6.8 compiled on Jul 21 2019 at 18:50:52
with support for: ReadLine, RPlay, Stroke, XPM, SVG, Shape, XShm, SM, Bidi text, Xinerama, XRender, XCursor, XFT, NLS`

**Comment by NsCDE** [comment]
This is exactly the same setup as on my Debian system. Only difference is /opt/NsCDE should be owned by root and not group readable, but this is for sure not a cause of this mistery. Most probably there is some trivial permission or something like that on your sistem which is causing this.

You can try to start X session without window manager (just one xterm), and then run manually /opt/NsCDE/bin/nscde (remove redirection to the /tmp/debugging_nscde.log) to see what will happen.

P. S.
Probably irrelevant, but which display manager are you using?

**Comment by pavroo** [comment]
Owned /opt/NsCDE/* by root, no changes.
Removed Debian's fvwm and installed 2.6.9 from source, no changes.
Removed NsCDE rc24 and installed back rc21, works like a charm (via lightdm).

**Comment by NsCDE** [comment]
I'm having red rash of this already. I cannot start to debug anything because here everything works.

Maybe Installer.ksh has some bug. Maybe NsCDE-Main.conf is not sed-ed correctly during installation.

Please do for me this:

cat /usr/share/xsessions/nscde.desktop

Pack and send me your /opt/NsCDE/config/NsCDE-Main.conf and /opt/NsCDE/bin/nscde from rc24 for inspection. Not files from installation, but files which are already installed on your system.

And just in case this:

ls -ld /
ls -ld /opt
ls -ld /opt/NsCDE
ls -ld /opt/NsCDE/config

By fixing this, maybe I can catch and prevent such situations in the  future with additional checks.

**Comment by pavroo** [comment]
Here you are:
`cat /usr/share/xsessions/nscde.desktop
[Desktop Entry]
Encoding=UTF-8
Name=NsCDE
Comment=Not so Common Desktop Environment
Exec=/opt/NsCDE/bin/nscde
Terminal=False

[Window Manager]
SessionManaged=true`
`ls -ld /
drwxr-xr-x 20 root root 4096 Aug 31 10:02 /`
`ls -ld /opt
drwxr-xr-x 27 root root 4096 Sep  6 20:35 /opt`
`ls -ld /opt/NsCDE
drwxr-xr-x 7 root root 4096 Sep  6 20:35 /opt/NsCDE`
`ls -ld /opt/NsCDE/config
drwxrwxr-x 3 root root 4096 Sep  1 23:00 /opt/NsCDE/config
[nscde-rc24-20200906.zip](https://github.com/NsCDE/NsCDE/files/5180132/nscde-rc24-20200906.zip)
`

**Comment by NsCDE** [comment]
Finally something!

NSCDE_ROOT - the most important variable is empty in "nscde" and NsCDE-Main.conf.

It sould point out to NsCDE installation (/opt/NsCDE by default).

Ok, the way you are using Installer.ksh is probably different from mine, but also legal if it worked for rc21. Please write me the exact options of Installer.ksh you use to install NsCDE, than I can see what I broke when I added -D option probably.

**Comment by NsCDE** [comment]
Got it. Installer.ksh misconfigures value of NSCDE_ROOT in interactive setup mode. Bug added with "-D <faketoot>" for packaging.

I usually install with "-w -n -i" flags, and this is non-interactive, where bug didn't manifested itself. I have fixed and commited now Installer.ksh in master branch and because this  can happen to great number of users, I will make fix release.

**Comment by pavroo** [comment]
Installed and works ok on Debian stable and testing.
Thanks
