### ISSUE TITLE
Enable Compiz / Smaller Taskbar

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [NsCDE/NsCDE#32]
I absolutely love NsCDE, but I have a couple issues with it.

First, I can't enable Compiz to eliminate screen tearing. When I try enabling Compiz with `compiz --replace`, I get logged out. Sign back in and screen tearing is still present. How would I enable Compiz?

Also, how would I make the taskbar smaller than currently allowed? I use NsCDE on a 1024x768 display and it's a bit too big for me.

**Comment by NsCDE** [comment]
1. Running `compiz --replace` will kill existing window manager (FVWM) and hence NsCDE, replacing it with itself, or logging you out if this does not suceed. Use picom or compton for compositing if you have to.

2. There is no taskbar in CDE and NsCDE. In NsCDE the closest match is WindowList which can be called by middle mouse click on a root window or with Alt+Esc. If you mean for Front Panel, then no: it is fixed in size. 1024x768 is the smallest supported resolution. However, it will go into background when not focused, and can be called back with Ctrl+Escape or it can be rolled to thin dash at the bottom of the screen with Shift+Escape and rolled back with the same key binding.
