### ISSUE TITLE
(request) right click on title bar

### ISSUE THREAD

**Issue by brightersun99** [NsCDE/NsCDE#41]
On the normal CDE desktop, you are able to right click anywhere in the title bar to get to the menu for managing that window. 

On NSCde, you have to click the - icon, which is the case for cde too, however, on CDE you can do both, it is nice. 

I must also ask, is it possible to run the themeing utility stand alone? I often set it to make apps look better with real CDE.

**Comment by danger89** [comment]
Right click on title bar causing to the window already to minimize, right?

**Comment by NsCDE** [comment]
Indeed. Right click will bring the same window operations menu as a click on the first (leftmost) button on the title bar under CDE, while in NsCDE will act as a fast Raise/Lower mechanism, due to 1st click beeing sometimes slow (if mouse is not imeddiately moved) or unprecise due to fact it serves as move AND raise/lower mechanism.

You can override and re-configure this in the local ~/.NsCDE/NsCDE-Keybindings.local file:

`Mouse 3 T A Menu m_WindowOpsStandard`

... to get exact CDE behaviour.
