### ISSUE TITLE
sysctl suspend/reboot/etc. fail w/ sudo

### ISSUE THREAD

**Issue by rtomsick** [NsCDE/NsCDE#5]
## Environment
* Stock Fedora 31 installation
* NsCDE installed, all settings defaults
* single user account, not sudoer (i.e. I set an "admin" (root) password during install)

## Steps to reproduce
1. Open the system dialog.
2. Select Suspend, Reboot, Shutdown, or other actions handled by nscde-acpi
3. Click 'Confirm'

## Expected Result

System restarts, shuts down, suspends, etc. as requested.

## Actual Result

Nothing.  It's a silent failure with zero user feedback.  It just... doesn't work.

Executing the relevant command by directly invoking `nscde-acpi` directly works fine.

## Root cause

The `SysActionDialog` script executes the `nscde-acpi` wrapper prefixing the command w/ `sudo` even if it doesn't need to.

## Implementation Suggestion 

Having to start using sudo just for this isn't a great user experience.  But on a modern Fedora install like this I *don't* need to have sudo just to suspend w/ systemd.  (And given that systemd is all but universal on Linux nowadays, anyone still using the legacy methods is probably used to doing lots and lots of manual config. :wink: )

It will make the `nscde-acpi` wrapper slightly more complex, but it might not be a bad idea to reduce the use of `sudo` only to what's strictly required.  That should improve the default experience, not to mention make it easier for people who won't or can't give sudo to the user accounts.

And no, FreeBSD won't be handled out of the box, but we're used to that too. :laughing: 

(Bonus points: add a "lock + sleep" option that calls Xscreensaver before calling the wrapper.)

**Comment by NsCDE** [comment]
Hello again.

I wasn't aware  that "systemctl suspend" is going to work for a ordinary user just like that. Without sudo, without beeing in the wheel or some group. Everyone can freeze the system and this is default configuration out of the box. Looks like it uses that "polkit" for this preauthorization. I have just confirmed what you wrote in KVM on Fedora 31 VM. Scarry when system is not actually one-user laptop or desktop!

After googling a bit, I see some people are disabling this and use sudo anyway. Some are using pm-tools on older systems as I on CentOS 7 which is still my primary.

This complicates things. I need to detect what works and what is not working. I must try on Arch VM and so on ... I will like to autodetect this and not confront user with configuration if possible.

Couple of other things:

1. Default heavyweight display manager GDM on Fedora 31 will prevent X output to go into .xsession-errors. As user, run "journalctl -t /usr/libexec/gdm-x-session -f" to see diagnostic. You can make local customization of "NsCDE Log" on 7th subpanel to use this instead of tail -f .xsession-errors.

2. FreeBSD ... this people are used to make things manually step by step as you said also. They can install sudo with pkg. :)

3. Lock: thanks for pointing this out. I forgot that xsceensaver is handled on my system by custom script of pm-utils, and didn't really tested suspend on virtual environment. This needs to be fixed.

Leave this open. It's almost 3 am here, and I neither can sleep nor work because of flu or cold or whatever I got today. This are actually 2 issues: systemctl without sudo and xscreensaver handling. Will take a look today or tomorrow. Thanks for pointing this out, however I'm not really comfortable with this systemctl suspend: who knows what it can do apart from suspending system as ordinary user!

In the meantime see example for sudo if you didn't already.
/opt/NsCDE/share/doc/examples/sudo/006_PowerManager

**Comment by NsCDE** [comment]
I have solved this with calling acpi by calling it with "sudo -n" and if it fails, then the same command without sudo. A bit ugly, but this was the only way not to put sudo in the script, which can then complicate possible configuration layouts for people using it.

BTW, on CentOS 7 systemctl suspend is also no enabled for user without sudo.

Before suspend/hybrid/hibernate, xscreensaver should be activated in lock mode now (if it is not disabled in NsCDE.conf).

Many other fixes.

**Comment by rtomsick** [comment]
Great, thanks!  Ugly beats non-working any day of the week!

I'm not surprised that CentOS works that way.  IIRC that's been the behavior for suspend/halt via systemd in RedHat-land for a while now.  So it makes sense that all of Fedora, CentOS, RHEL and derivatives work that way.  It's a bit of a change from the old school "root controls physical operations" but a pretty defensible one for modern workstation/laptop use cases.  After all, when was the last time you saw a workstation w/ several people using it simultaneously like in 1990s computer labs?  (And yes, it's trivial to lock down on for server use cases. :smile: )

**Comment by NsCDE** [comment]
Well, yes. I have read that action is somehow confined to local access. Of course we don't have many such machines in the modern world, but I was concerned for remote non-desktop, user: let's say developer who you must give account for upload and few setups and commands. This polkit "local only" authorization policy confines this to "physical" user. At least in theory. :)

**Comment by rtomsick** [comment]
I think polkit's enforcement code is pretty battle tested at this
point.  It's not as scary as it seems at first glance. :D
