### ISSUE TITLE
The Return of the Son of /opt/NsCDE/libexec/nscde-acpi

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#50]
Hi,
sorry to bother you again about this, but I tried to reboot my MX Linux desktop from NsCDE and received again (in)famous error:
"System has not been booted with systemd as init system (PID 1). Can't operate"
It look like it's necessary modify "f_reboot" the same way you did for "f_poweroff" in that script; I'm sorry for not noticing and reporting this before, the fact is I don't reboot my desktop very often.
While I was at it, I tried the other /opt/NsCDE/libexec/nscde-acpi options and seen that for 'suspend', 'hibernate' and 'hybrid-suspend' the userid should be allowed to 'sudo' the corresponding 'pm-utils', so I noticed a small discrepancy between the documentation and the actual NsCDE directories contents: chapter "8.1. System Tree Layout" says that in 'share/doc/examples' one could find examples for 'sudo' those 'pm-utils', but I couldn't find any.
That's not a problem at all for me, but I'd like to report it to you anyway, in case such small discrepancy wasn't intended. (and unless I'm missing something, or course)
Thanks

**Comment by NsCDE** [comment]
Hi @leoctrl 

You are not bothering, you are helping.

Thanks for spotting this. I don't know how I forgot to put systemd check for reboot and even omitted to test this in MX Linux VM. Fixed in master tree few minutes ago.

Examples for sudo are really in $NSCDE_ROOT/ (/opt/NsCDE/ usually) share/doc/examples - subdirectory sudo contains 006_PowerManager file.
