### ISSUE TITLE
Custom cursor

### ISSUE THREAD

**Issue by Wolfnya** [NsCDE/NsCDE#54]
How i can change the cursor ? i want make my cursor like red cursor in SGI IRIX  OS

**Comment by NsCDE** [comment]
Hi @Wolfnya

Cursor theme used by X and GTK/Qt is not under control of the NsCDE nor FVWM. The only thing NsCDE does during initial setup for user session is to put "dmz-aa" in $HOME/.icons/default/index.theme to avoid any cursor themes which may be imposed by graphical login manager in order to have vanilla X11 look as in CDE. Only exception beeing sandglass hour busy cursor which is configured with CursorStyle FVWM directive in /opt/NsCDE/config/NsCDE-Style.conf, but can be overriden in $FVWM_USERDIR/NsCDE-Style.local.

GTK/Qt cursor theme can be changed afterwards and will not be overwritten by NsCDE style managers. Search the web for "linux cursor themes" or X11 cursor themes. Here is the one looking nice: https://wiki.archlinux.org/title/Cursor_themes
