### ISSUE TITLE
Is there a way to tame the Evince PDF viewer?

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#56]
Hi, I wonder whether Fvwm or NsCDE can command Evince to behave.
I like that application, but it hasn't got a tabbed view, which means that every document has to be opened in a separate window; now, my problem is that when it comes to opening new windows Evince has a mind of its own: each new window gets an initial different size, and in some cases they've been created larger than the screen(!)
Needless to say, there's no option in Evince (at least, in the version that comes with my distribution) to set an initial window size.
I tried NsCDE's GeoDB, but I found out that it only worked for the first Evince window, other windows still get their initial size at random.
I checked the documentation of Fvwm's Style directive, but I only found things like MinWindowSize and MaxWindowSize, if I'm not mistaken there isn't any style option to set the initial size of a window.
Based on your experience, is there anything you can suggest?
Thanks

**Comment by NsCDE** [comment]
Hi @leoctrl 

NsCDE Geometry Manager works for first window on a page/desk. Otherwise, windows of the same type will overlap in a pixel, which is not convinient. Most probably optimal behaviour should be to open them in a cascade down-left or down-right or so, but this is not (yet) achieved.

Try Fvwm Style InitialMapCommand and put there something like "ResizeMove x y X Y" see fvwm man page. If it misbehaves again while opening the document, try to prefix ResizeMove with Schedule 500 for example.

BTW, have you tried qpdfview? Nice tabbed, with lots of features. Well behaved, it even has a title bar. :)

**Comment by leoctrl** [comment]
Yes, I have both qpdfview and Evince installed, but in some cases Evince renders pdfs better, and it also lists all results of a text search in the side pane, which comes in handy, so I often use the latter.
Back to your response, indeed Style InitialMapCommand + a little delay with Schedule did the trick!
Thanks!
