### ISSUE TITLE
Converting backdrop images

### ISSUE THREAD

**Issue by fn-ix** [NsCDE/NsCDE#76]
Hello! Is there an easy way to convert the PageMaker images to a more modern format? I tried `soffice --headless --convert-to jpg *.pm` but just ended up with images of text.

**Comment by NsCDE** [comment]
So you are actually operating on souce backdrop files, not (x)pm icons. This (x)pm files are templates, and their hex color codes are merely place holders for colors produced by Backdrop Style Manager. Turns out this one has incorrect two letters more than normally should have color hex of XPM file, so it is corrupted if used directly, but handled normally by the Backdrop Style Manager.

Just open it with editor and remove last "E2" from the end, and it will become usable for direct displaying again.
