### ISSUE TITLE
Issue with renaming workspaces

### ISSUE THREAD

**Issue by christian-moerz** [NsCDE/NsCDE#79]
In version 1.3, there appears to be two issues in renaming workspaces. As far as I can tell, there are two ways to renaming workspaces: right-clicking a workspace button in the middle of the center bar (i.e. "One" / "Two" / ...), the widget turns into a textbox that can be edited. In my instance, this turns into a white textbox with white text. I can't say, whether this is due to my selected color scheme or a bug. 

In my particular instance, I cannot complete the edit process. Pressing enter does not complete the edit; I'm kind of left stuck with a cursor in the button and can no longer press the workspace button until I completely restart nscde.

Then, one can click "Manage" and open a separate application, that mirrors the four workspace buttons. Clicking on one button, it again turns into an edit box. This box is also white text on white background for me, however it allows me to complete the edit by pressing enter. Going this route successfully leads to a renamed workspace button.

However, in the "watch errors" app, I get error messages like the following
[WSM-4] Line 591: syntax error
The number obviously changes depending on which workspace button is being edited.

Looking into WSM, line 591 says
ChangeTitle $DeskToRename $NewDeskName (Gettext {|Rename ...|Manage ...|Go to Page ...|Local Pager|Windows ...})

Not sure, what's wrong about this line? Any way to fix this?

I'm running on FreeBSD and using nscde from ports.

If you need any further details, please let me know.

Thanks

**Comment by NsCDE** [comment]
Hello @christian-moerz 

It will be nice if you tell me what color scheme you are using, so I can try to reproduce this white on white. It is strange that this happens because this is FvwmScript TextField widget bug under some circumstances, which has been worked around by NsCDE long ago. So please: color scheme name.

Second, it is Ctrl+Enter, not only enter. There is a good reason for that, because renaming process cannot steal enter only for itself.

For refreshing Front Panel it is enough to click on the leftmost top button NW of clock, and choose "Front Panel Controls" there is no need to restart the whole thing.

Line 591 in WSM has been fixed 2-3 weeks ago. It was mostly harmless (parser inability to cope with complexity). You can update from git master tree. It contains only fixes after 1.3.

So color scheme info will be nice ...

**Comment by christian-moerz** [comment]
Thanks for the feedback; that hint about the Front Panel Controls really is helpful - didn't even realize it was there. Just restarting the workspace manager does the trick when it's stuck.

I'm running on the "Solaris" color scheme. I could also provide details from my config files, if that helps.

That's what it looks like for me - you can see the ^ cursor after typing some characters.
![Screenshot_2021-11-13_10-22-57](https://user-images.githubusercontent.com/60877824/141613670-922ae6a9-40cc-4610-af08-61b367dfb062.png)

**Comment by NsCDE** [comment]
Hi @christian-moerz 

I see. I can reproduce white on #fff7e9  (almost white), but Ctrl+Enter works every time.

First, for a consistent behaviour of keybindings, turn off num lock on keyboard. For a details, see IgnoreModifiers in fvwm(1) man page. Then, Ctrl+Enter should work,

Try this please: when you click the button which you want to rename, press Ctrl+Space to enter rename. That way, you should avoid white-on-white bug.

In the meantime, I will investigate how to convince TextField to behave with bg/fg colors in this situations. Thanks for this report.

**Comment by christian-moerz** [comment]
Hah, yes. That's interesting. Turning off NumLock really makes it work. Quite unexpected, but totally makes sense with the modifiers. Thanks!

**Comment by NsCDE** [comment]
BTW @christian-moerz I have hardened workaround for white-on-white, and now it should be 99% ok. Also I have put notice popup about Ctrl+Enter in the master. If you want, you can use WSM* from the master in place of old 1.3 files from ports, just replace them.
