### ISSUE TITLE
CDE Colors theming ?

### ISSUE THREAD

**Issue by enigma131** [NsCDE/NsCDE#89]
HI, I've discovered this development since few days and playing with after installing both CDE and NsCDE on SparkyLinux Minimal.
Nice work, it remembers me the HP 9000 Unix from the 90's
As I have installed both desktops, i have add a link to /usr/dt/bin/dtclock in a sub-panel. It works but I haven't original colors :
Under NsCDE : 
![DtCalc](https://user-images.githubusercontent.com/31815445/148565560-1c24d5e6-fc9b-4d52-a246-244c49288cd7.png)
Under CDE:
![D0](https://user-images.githubusercontent.com/31815445/148566704-1ef77add-2aa8-40e0-9b5e-cdd1a28e668d.jpg)
How to get same colors ?
Gtk problems ?
Ah, colors settings are same in both desktops.

**Comment by NsCDE** [comment]
Hi @enigma131 

CDE dtsession(1) uses it's own color management, and it is not clear to me how it communicates this to the programs without X resource database record. It is even not clear how it decides which buttons of dtcalc to colorize in which of the 8 colors from the active palette. Dtcalc is the only such example, because all other Motif programs are covered by the X resources of NsCDE in ~/.NsCDE/Xdefaults. BTW, this is nothing to do with GTK, because dtcalc is a Motif, not GTK application.

You basically have two options here:

1. painfully using editres(1) to catch exact button names or their parent Motif objects and colorize this in ~/.NsCDE/Xdefaults.local
2. Running NsCDE from the dtsession instead of dtwm. See wmStartupCommand in dtsession(1) man page. While under dtsession, NsCDE will inherit this shady unknown source of colors which is not in app-defaults files nor in X Resource Database (xrdb) and programs will show exact coloring as  in CDE (in practice, only dtcalc I think will be different).

**Comment by enigma131** [comment]
Hi, thanks for answer. 
Point 2 seems more useful but I don't see how to make it in order.  I've installed lightdm as X display manager (switch between CDE, NsCDE and fvwm. Installation was made with SparkyLinux minimal CLI iso.

**Comment by NsCDE** [comment]
By putting Dtsession*wmStartupCommand: <PATH>/bin/nscde in ~/.Xdefaults and logging into CDE from display manager. You will then get CDE session managed NsCDE.

**Comment by enigma131** [comment]
The file wasen't created, I've create it and put in the command. After correction <PATH>/bin/nscde to /usr/bin/nscde, NsCDE starts and I have right colors for the calculator. Welldone.
But here a new problem: some startup scripts didn't start, example gkrellm didn't start automaticly but via terminal.

**Comment by enigma131** [comment]
Ok thanks
