### ISSUE TITLE
No motif titlebar on some Gnome applications

### ISSUE THREAD

**Issue by enigma131** [NsCDE/NsCDE#90]
I've installed gnome-disk-utility and this one have the problem.
It's strange because when i remove header for Firefox in it's own menu , motif is still ahead...
The gnome-disks is very popular (mounting unmounting devices, formatting, Smart datas for disks) .. , it's working , but if i don't look for cosmetics but functionality, motif closing is at top left and for this one at top right.
Some way to solve the issue ? Or an alternative software ?

**Comment by NsCDE** [comment]
Hi @enigma131 

I have read what you wrote 3 times, and I'm really not sure what are you writing about. What is here exactly "header" and what "motif"? Motif here is probably not a motif library ...

I have put this gnome-disk-utility in one VM now to examine. It looks awful as all GNOME apps, but looks as it is functional (as much as some GNOME application can be functional that is).

What is the problem?

**Comment by enigma131** [comment]
Yes i wrote the same thing, It is functional. But why it is look awful, and why didn't we have closing menu a top left as other apps ?

**Comment by NsCDE** [comment]
I have tried it now under NsCDE GTK theme and default Adwaita theme. Buttons or menus (or whatever this thing is) are on the same places in both cases. This is how application was written. How does NsCDE has anything with that? NsCDE cannot influence on every aspect of every application.

P. S.
If you are asking about FVWM titlebar with titlebar buttons 1 (left) and 2 and 3 right, this is because that crappy GNOME thing is giving hints to the window managers that it doesn't need their decorations (titlebar, corners, borders, buttons ...).

Search your system repository, or google for gtk3-nocsd hack. It is available in Debian by default for example. Install that and configure to LD_PRELOAD in your X session to cheat GNOME apps and you will get back standard behaviour.

**Comment by enigma131** [comment]
Yes, the right term is tile bar, thanks to remind me.
I will look for gtk3-nocsd to solve this crappy (but useful) Gnome's title bar app.

**Comment by enigma131** [comment]
It's working, exactly what I was searching for. Could be pinned for others..
In  .bashrc i have added : 
export GTK_CSD=0
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0
Taken from gtk3-nocsd's gihub
For Arch system settings would be different.
Thanks.

**Comment by NsCDE** [comment]
I'm glad we figured it out and solved.
