### ISSUE TITLE
Style Manager warning message and problem with two of the same colors.

### ISSUE THREAD

**Issue by rasatpc** [NsCDE/NsCDE#95]
Add a warning message when changing the color palette because the default “Apply” changes all user settings of different WMs (not DEs). Accidentally someone may press Apply instead of Close. Also, there is an unrepairable case when selecting two of the same colors. It doesn’t generate 8 but 7 colors. Everything becomes grey. The only solution is to delete /.NsCDE and reinstall.

**Comment by NsCDE** [comment]
Hi

1. As I wrote you in [FVWM forum](https://fvwmforums.org/t/nscde-releases-changes-and-announcements/2782/53), this changes for GTK2, GTK3, Qt4 and Qt5 GUI widgets are harmless, and can easly be reversed or changed manually, or with appropriate GUI tools.
There are **no ways** (at least not known to me) to redirect all this libraries with environment variables or similar mechanism to read for example ~/.NsCDE/gtk/2/gtkrc, ~/.NsCDE/gtk3/gtkrc or ~/.NsCDE/qt5ct/qt5ct.conf as it is done for stalonatray and dunst for example with separate NsCDE config. If you are aware or know elegant and error prone way how to have GTK and Qt options read from alternative source under NsCDE, I will be glad to implement it. In the meantime, this 2-3 parameters in gtkrc and qt5ct.conf can really be reversed manually in a minute if needed. Backing up and restoring is not an option. Every shutdown without logout, violet shutdown or crash will leave things unrestored, causing unpredictable behaviour experience from the user's perspective. Bind mounts and other non-portable hacks are also not an option.

2. What do you mean by "Also, there is an unrepairable case when selecting two of the same colors. It doesn’t generate 8 but 7 colors." ? Modify Color feature of Color Style Manager always works with ONE color, selecting one of 8 colors is exclusive operation. No 2 or more colors can be selected. From this description, I'm not sure how you managed to generate broken palette file, but deleting whole ~/.NsCDE is totally unnecessary even when this happens somehow, repeated run of Color Style Manager with some other palette will rewrite everything and fix.

**Comment by rasatpc** [comment]
In this report (point 1), I am not asking to change the libraries, but to add an additional confirmation to the Apply button in Style Manager. Earlier I have received complaints when new users are testing NsCDE, they accidentally pressed Apply instead of Close. Last week, I did the same mistake.

**Comment by rasatpc** [comment]
(Pont 2). I made one new test. In "Style Manager-Color" by modifying Broica's 1st button to black color, apply and save in /palettes/Custom.dp. There are 8 colors.

```
#000000000000
#999999999999
#89899898aaaa
#68686f6f8282
#c6c6b2b2a8a8
#49499292a7a7
#b7b787878d8d
#9393ababbfbf
```
Next, the 5th button to black color, apply and save in /palettes/Custom.dp. There are 7 colors.

```
#000000000000
#49499292a7a7
#b7b787878d8d
#9393ababbfbf
#999999999999
#89899898aaaa
#68686f6f8282
```
Everything becomes in grey color. This can be fixed by changing the colors in Style Manager. But, if logging out from NsCDE and login in again, the Style Manager cannot fix it. Each and every sample colors are grey.

The solution to this issue is to not allow a user to apply two of the same colors. The Style Manager tool has to check/stop and warn the user when this is happening. Thereby the user makes a slight unnoticeable change in the 2nd color and things work fine.

**Comment by NsCDE** [comment]
Hi

You have found really nasty bug in FvwmScript For loop which truncates same values if they follow one after another. Modifying colors 1 and 5, 2 and 6, 3 and 7 ... in a way to have exactly the same hex, resulted in non-printed value, and hence invalid CDE palette file. BTW, no matter if samples looks gray, fix will always work. Deleting the whole setup is tedious.

I have implemented workaround for above mentioned situation in the current master now.

BTW, putting dialog after hitting Apply - then it must be also for "OK" because they are doing the same thing, but "OK" additionally refreshes and restarts FVWM. This is more work to do. It will be in 2.1 according to GTK and QT checkboxes. Probably descriptive dialog which will tell "this will change your GTK or QT theme from "Oxygen" to "NsCDE" and icon theme from "Breeze" to "NsCDE" in that and that config file" - if they are initially different there of course. This part of Color Style Manager must be rewritten anyway, because Qt will have Kvantum engine alternative to gtk2 in 2.1.

**Comment by rasatpc** [comment]
> I have implemented workaround for above mentioned situation in the current master now.
Thanks, works fine. Made a test with the two black colors and looks good.

About point 1, if I remember correctly, Fluxbox had the same behavior of affecting the GTK2, GTK3, etc. of other WMs. MX Linux made a change and Fluxbox has now its own /.fluxbox/styles/. I will check on this.

**Comment by rasatpc** [comment]
I did a test on CDE with Sparky Linux to have a look at the original look and feel. First, The color settings have no effect on the look of the applications besides the window title bar and frame. So, there is no need to go change the gtkrc-2.0 and gtk-3.0 settings. It looks beautiful with CDE’s own color. I suggest putting NsCDE back in the CDE coloring system as shown in the below screenshot. I selected one of the color schemes and changed button 1 to black color. Click below link.  Thunar file manager didn’t get affected by CDE’s color change. This is how it should work.
https://rasatpc.net/screenshot/NsCDE/cde-color-manager.png

**Comment by NsCDE** [comment]
I think you miss the point of NsCDE.

One of the key points is to **integrate** applications from various backgrounds. This includes GTK 2/3 and Qt 4/5 in the first place, as well as for legacy Motif and Athena apps.

CDE also does this with X resources and it's dtsession(1) daemon for all application types which were known at the time when CDE was in more active state (Motif, Xt ...). There was no GTK nor Qt back then, and even later, at the beginnig of the 21 century they were not so popular in comercial UNIX world to be considered for integration. Moreover that they do not use X toolkit in a way Motif and Athena were using. Even more, some people actually **use** original CDE with NsCDE theme parts for GTK and Qt, plus icon theme.

Apart from better window manager, there is not much point using NsCDE without integration of modern GUI widgets and XDG concepts in it. CDE is more then enough for what you think how it should work, and may be used instead of NsCDE if such setup is desired.

Even if NsCDE is used, it's Color Style Manager always offers checkboxes to deselect one or more such integrations for whatever reason for user's convenience.

**Comment by rasatpc** [comment]
> ...there is not much point using NsCDE without integration of modern GUI widgets and XDG concepts in it.
I am taking interest in NsCDE to include the current 55 myExt extensions. With a minor change from using on Fvwm3, they work fine. When I get time, planning to make one short video. Check the screenshot.
https://rasatpc.net/screenshot/NsCDE/NsCDE-myExt3-modern2.png
