### ISSUE TITLE
Front Panel not always showing correct workspace (multihead)

### ISSUE THREAD

**Issue by no3m** [NsCDE/NsCDE#99]
In a multihead environment, with the workspace model set to "Per-Desktop", moving the Front Panel to another monitor using Ctrl+Esc does not always reflect the currently selected workspace on the destination monitor, but rather the active workspace on the previous monitor.  Another Ctrl+Esc combo corrects the workspace selection on the Front Panel.

**Comment by NsCDE** [comment]
I'm aware of this.

It is happening when Front Panel is moved to the other monitor and there is no window below your pointer. If you prepare in advance a window, position mouse on it, and press Ctrl+Esc to move Front Panel, then it will trigger the change.

I'm waiting for this to be fixed in fvwm3: https://github.com/fvwmorg/fvwm3/issues/604

In the meantime, I will try to see if there is any alternative to trigger change in WSM on the Front Panel in such case by other means.

**Comment by NsCDE** [comment]
@no3m 

You can temporary help yourself by editing /usr/share/NsCDE/fvvwm/Functions.fvwmconf

Replace in function f_RestoreFrontPanel (around line 572) last two lines:

```
+ I Test (EnvMatch FVWM_IS_FVWM3 1) f_SendToWSM
+ I Test (EnvMatch FVWM_IS_FVWM3 1) Schedule 1500 f_SendToPGM
```

with:

```
+ I Test (EnvMatch FVWM_IS_FVWM3 1) Exec exec nscde_fvwmclnt 'f_SendToWSM'
+ I Test (EnvMatch FVWM_IS_FVWM3 1) Exec exec nscde_fvwmclnt 'f_SendToPGM'
```

This is a cludge. Temporary solution.

**Comment by NsCDE** [comment]
Even better. Probably should be permanent solution:

```
+ I Test (EnvMatch FVWM_IS_FVWM3 1) NoWindow f_SendToWSM
+ I Test (EnvMatch FVWM_IS_FVWM3 1) NoWindow f_SendToPGM
```

**Comment by NsCDE** [comment]
Commited to master.
